### ISSUE TITLE
Trivial: consider dropping comment about dark theme

### ISSUE THREAD

**Issue by pabl0** [fniessen/emacs-leuven-theme#101]
Both variants of the theme have this under Commentary:

https://github.com/fniessen/emacs-leuven-theme/blob/28a2d1a3f22b894e1b973c62a6c78786cfe5ab1f/lisp/leuven-dark-theme.el#L38-L39

Isn't this exactly what leuven-dark-theme.el already implements? If so, perhaps this comment can be dropped.

Thank you for leuven. It is one of the more fresh themes out there.

**Comment by fniessen** [comment]
Hey @pabl0, I appreciate the attention to detail, even if it's nit-picking... So, really thanks for your input!

The issue has been addressed in commit 04ac63e.
