### ISSUE TITLE
Success and error faces hard to read

### ISSUE THREAD

**Issue by simenheg** [fniessen/emacs-leuven-theme#14]
I find the current `success` face is hard to read against the blue mode-line:

![success face example](http://i.imgur.com/X4SUbZb.png)

The `error` face is a bit better, but still a bit hard on the eyes:

![error face example](http://i.imgur.com/30FI6mG.png)

Any chance they could be tweaked a bit?

By the way, I want to thank you for providing this overall awesome Emacs theme. :)

**Comment by fniessen** [comment]
I've added something which will improve this. It maybe is not my final choice, but it should be better already. WDYT?

**Comment by simenheg** [comment]
I also find the new faces easier to read already. Thank you!
