### ISSUE TITLE
sx.el colors missing and unreadable

### ISSUE THREAD

**Issue by dakrone** [fniessen/emacs-leuven-theme#23]
Colors for [sx.el](https://github.com/vermiculus/sx.el) are missing, which causes the headline to show up like:

![screenshot_2015-09-29_07-08-45](https://cloud.githubusercontent.com/assets/19060/10164861/42765e36-6679-11e5-986b-3f5f86c88561.png)

And makes it really difficult to read the white-on-yellow

**Comment by fniessen** [comment]
Would you like to come up with a proposition, preferably as a code block which I can directly inject into the theme file, or as a GitHub PR?

**Comment by brabalan** [comment]
I guess the same colors are used for elfeed:
![screen shot 2016-01-14 at 14 54 22](https://cloud.githubusercontent.com/assets/1021637/12326079/d702e854-bace-11e5-9375-2dd1d0ce8db8.png)

I have no idea how themes work, however. I had a quick look at the code, and it seems the first step is to find the name of the face that one wants to change. Is it possible through the interface (taking into account the fact that I cannot move the cursor to that point), or can it only be done by looking at the code?

**Comment by brabalan** [comment]
I’ve looked into this, and both modes use `mode-line-buffer-id`. Elfeed declares a face for it:
``` emacs-lisp
  (defface elfeed-search-filter-face
    '((t :inherit mode-line-buffer-id))
    "Face for showing the current Elfeed search filter."
    :group 'elfeed)
```
so it can be easily changed, but sx does not:
``` emacs-lisp
(defconst sx-inbox--header-line
  '("    "
    (:propertize "n p j k" face mode-line-buffer-id)
    ": Navigate"
    "    "
```

@dakrone I guess you should file an issue with sx.el asking them to create a face that inherits from `mode-line-buffer-id` so that the leuven theme could customize it.

**Comment by fniessen** [comment]
@brabalan Thanks for looking into it.

Your recommandation is clearly the right one!  Best regards.

**Comment by brabalan** [comment]
@fniessen here is some code you could add to the theme for elfeed:
``` emacs-lisp
;; elfeed
`(elfeed-search-filter-face ((,class (:foreground "gray"))))
```

**Comment by fniessen** [comment]
Pushed.
