### ISSUE TITLE
hl-line-mode and org macros

### ISSUE THREAD

**Issue by brabalan** [fniessen/emacs-leuven-theme#25]
Using leuven theme, if hl-line-mode is on, the text of org-macros become impossible to read on the current line.
Line above:
![screen shot 2016-03-10 at 10 25 47](https://cloud.githubusercontent.com/assets/1021637/13665000/8b64fe84-e6aa-11e5-96cf-f279468eee88.png)
On the line:
![screen shot 2016-03-10 at 10 26 00](https://cloud.githubusercontent.com/assets/1021637/13665001/90b690c8-e6aa-11e5-9fb5-16ec00031fbe.png)

I guess the problem is that the org-macro face has Foreground as white, and this is not inverted with hl-line.

Is this possible to fix this on the leuven side, or is this an hl-line-mode bug?

**Comment by hkrish** [comment]
+1

**Comment by fniessen** [comment]
Sure, it must be fixed in Leuven. And, in fact, it already is since version 20141230.1549.  That's quite some time ago.

I deduce you use the version built in Emacs?  I should ask for an update there.

But, in the meantime, you better use the MELPA version of Leuven-theme.  You'll always be up-to-date, then!

Best regards.

**Comment by brabalan** [comment]
This is surprising, I'm using a version from MELPA, the 20160207.1043 to be precise. I don't know if it mattered but I'm using this as part of spacemacs.

**Comment by fniessen** [comment]
Yes, it must matter then. I'm sure there is a default theme in there, and somehow such conflicts happen.  Is this a question of load order?  Is this because applying a theme doesn't reset everything?  But it must be key to understand the real problem.

**Comment by brabalan** [comment]
For the record, the problem was that the theme was set before packages were loaded, so I was getting the built-in version from 2014. Manually loading the theme again after loading packages works.
