### ISSUE TITLE
highlight-sexp-mode

### ISSUE THREAD

**Issue by davorb** [fniessen/emacs-leuven-theme#26]
Highlight-sexp-mode doesn't work well with this theme because a value for the variable ```hl-sexp-background-color``` is missing. 

Here's what doing ```(setf hl-sexp-background-color "#efebe9")``` does

![image](https://cloud.githubusercontent.com/assets/798427/13729567/1cee9a06-e938-11e5-9e81-dd9639236aad.png)

**Comment by fniessen** [comment]
Is this OK?

**Comment by davorb** [comment]
Looks great.
