### ISSUE TITLE
Highlight narrow nobreak-space

### ISSUE THREAD

**Issue by brabalan** [fniessen/emacs-leuven-theme#27]
I really like how Leuven highlights nobreak-space. When I write in French, I use narrow nobreak-space before some punctuation. Could it be possible to highlight those as well?

Here is what `describe-char` says about this character:
```
            character:   (displayed as  ) (codepoint 8239, #o20057, #x202f)
    preferred charset: unicode (Unicode (ISO10646))
code point in charset: 0x202F
               script: symbol
               syntax: . 	which means: punctuation
             category: .:Base
             to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"
          buffer code: #xE2 #x80 #xAF
            file code: #xE2 #x80 #xAF (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    mac-ct:-*-Source Code Pro-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1 (#x602)

Character code properties: customize what to show
  name: NARROW NO-BREAK SPACE
  general-category: Zs (Separator, Space)
  decomposition: (noBreak 32) (noBreak ' ')
```

**Comment by fniessen** [comment]
Are you using Leuven and/or Leuven-theme?

I have no problem adding support for narrow nobreaks, but what's the name of the face that's applied onto them?  Which package does that -- or do you use standard Emacs support?

But, as you show it above, there is no "face" overlay nor "face" text property there. So, the problem is not choosing a nice design for a specific face; but, first, to have a face applied on such characters...

**Comment by brabalan** [comment]
I'm using leuven-theme in spacemacs. And I see when I look at a normal NO-BREAK SPACE that it has an hardcoded face property, which the NARROW version lacks. I tried to find out how to add that property but did not succeed. In any case, I agree it's not a leuven-theme issue. Sorry for the noise.

**Comment by fniessen** [comment]
Have a look at my section 14.16 (Useless spaces) in my emacs-leuven configuration (same goal as spacemacs).

My config seems to handle the narrow nbsp. Have a look and see whether you can have a different face applied, eventually.

**Comment by brabalan** [comment]
I managed to make this work:
``` emacs-lisp
(font-lock-add-keywords 'message-mode '((" " . 'nobreak-space)))
```

Thanks for the hint!

**Comment by fniessen** [comment]
No need to do anything anywhere, right?

**Comment by brabalan** [comment]
Yes, there is nothing to do on Leuven's side. Thanks!
