### ISSUE TITLE
[FEATURE] Leuven for highlighting class and method names

### ISSUE THREAD

**Issue by MelleB** [fniessen/emacs-leuven-theme#29]
Hi,

I've been using the Leuven theme for a while, and it's really great!
As others said, not just for org-mode :)

Recently I've added highlighting for python classes and method definitions. It's pretty rudimentary, but it works. Maybe others like it as well, and maybe it's a nice feature to have not just for Python.

You can view the example here: https://gist.github.com/MelleB/920ad8e6c9d68a50b0670f72d324b284

Feel free to close this issue if you don't like the suggestion.

**Comment by fniessen** [comment]
I'm not sure it's here your suggestion should be sent -- it seems to be a patch for Python mode.

If something like that becomes "standard", of course I'm willing to get it properly displayed with Leuven theme. But I guess a patch is too early at this stage?  Or did you make progress on this?

**Comment by MelleB** [comment]
You're right. Another would be to wrap it up in a package of it's own and add support for multiple languages. Which I might do in the future... someday... :-) 

You can close this issue.
