### ISSUE TITLE
Please provide better default for helm-ff-dotted-directory

### ISSUE THREAD

**Issue by kostya-sh** [fniessen/emacs-leuven-theme#31]
Currently it looks quite ugly due to grey background (IMHO):

![emacs](https://cloud.githubusercontent.com/assets/7126275/16360914/c518266c-3bad-11e6-803e-6132c39eed08.png)

I think light blue or grey on white background would look much better.

Thank you.

**Comment by fniessen** [comment]
It seems to be a recent face.

I've added it. Cloning the directories in Dired.

Thanks for reporting the problem.

**Comment by kostya-sh** [comment]
Thanks for the quick fix!
