### ISSUE TITLE
change colors of the lucid toolkit?

### ISSUE THREAD

**Issue by zeltak** [fniessen/emacs-leuven-theme#37]
Hi, how are you?

well after about 5 years of using leuven i finally encountered something new :)

i changes the emacs GUI toolkit to lucid to avoid an X bug and i get really ugly faces in the menu

https://paste.xinu.at/5DBU/

i saw that other themes (such as solarized)  change the faces of the menu

any clue if we can have that in leuven?

best

Z

**Comment by fniessen** [comment]
Hi zeltak,

> Hi, how are you?

Fine, thank you.

> well after about 5 years of using leuven i finally encountered
> something new :)
>
> i changes the emacs GUI toolkit to lucid to avoid an X bug and i get
> really ugly faces in the menu
>
> https://paste.xinu.at/5DBU/
>
> i saw that other themes (such as solarized) change the faces of the
> menu
>
> any clue if we can have that in leuven?

You could try to duplicate, or modify, the following line:

   `(cursor ((,class (:background "#0FB300"))))

replacing `cursor' by `menu' -- this is the only term in Solarized that
gets my attention. Not sure what the right face should be customized.

Tell me if that works -- after reloading the theme...

Best regards,
Fabrice

**Comment by zeltak** [comment]
yup that did the trick! its perfect!
thx so much. 

Z

**Comment by fniessen** [comment]
Could you give the line you've customized therefore?  I will insert it by default, then.

**Comment by zeltak** [comment]
ahh sorry i just followed what you suggested, its:

```
;;; lucid toolkit emacs menus 
`(menu ((,class (:foreground "#FFFFFF" :background "#333333"))))
```

thx again!

z
