### ISSUE TITLE
tags, number of spaces, and visual-line-mode

### ISSUE THREAD

**Issue by brabalan** [fniessen/emacs-leuven-theme#41]
When using bigger headlines (`leuven-scale-outline-headlines`), the number of spaces before the tags is not modified, hence tags end up outside the frame (my frames are about 85 characters wide). This is even worse when using `visual-line-mode` as headlines with tags now take two lines.

Is it possible to reduce the number of spaces before the tags when using bigger headlines?

**Comment by fniessen** [comment]
This can't be solved by a color theme.  And this depends on your own settings (see org-tags-column).

Though, if that's annoying to you, you can try using unscaled outlines, or (soon!) to define yourself the scaling ratio. You could then find some sort of tradeoff...

**Comment by brabalan** [comment]
Thanks for the quick reply. I'm using unscaled outlines at the moment, which are less pretty but work.
