### ISSUE TITLE
minibuffer height changes constantly when moving cursor across orgmode buffer

### ISSUE THREAD

**Issue by et2010** [fniessen/emacs-leuven-theme#42]
When I move cursor up/down in orgmode, the minibuffer will echo the heading and since the heading line is taller than others, the height of minibuffer will change constantly when I do so. I find it's annoying. Is there a way to fix this? Thanks!

BTW, the variable `resize-mini-windows` is set to `grow-only`, and `leuven-scale-outline-headlines` and `leuven-scale-org-agenda-structure` are both set to `nil`.

**Comment by fniessen** [comment]
Dear, I don't have that behavior; never saw it (for years). Using GNU Emacs 25.2 on Windows right now.
See video at https://www.screencast.com/t/9PIvq31Jj9rg.

Can you test with a minimal Emacs configuration?  Can you test with another version of Emacs?  Or with other themes?

**Comment by et2010** [comment]
Sorry for the delay. I can't see the video but here's what I got on my computer:

![leuven](https://cloud.githubusercontent.com/assets/11584902/24793458/b8e32648-1bb4-11e7-9285-ee7ca3a2eb26.gif)

I didn't figure out how to use leuven theme with a minimal configuration on spacemacs. I tried spacemacs-dark theme, it has the same behavior but that theme scales the org heading font and has no option to turn off the scaling. So I don't think that will help.

Do you have any idea what is causing this? Thanks!

**Comment by fniessen** [comment]
OK, it's now clear what you meant. I was thinking you were switching between buffers (with C-x o).

Indeed, I also experience what you show. I will have a look at it.

**Comment by fniessen** [comment]
Dear @et2010 , would you wanna try setting `leuven-scale-outline-headlines` to `nil`?
