### ISSUE TITLE
Agenda font sizes causes org-column view to be misaligned

### ISSUE THREAD

**Issue by dakrone** [fniessen/emacs-leuven-theme#43]
When I hit `C-c C-x C-c` in org-agenda, the columns for the column view are not aligned due to the section headers:

![screenshot_2017-04-12_10-44-46](https://cloud.githubusercontent.com/assets/19060/24969794/399436f2-1f6f-11e7-8f9c-3e177f365fa8.png)

If I invoke `org-columns` in my regular org-mode file, the headlines (which are usually larger) use a smaller font so that the table is aligned, see the before and after pictures:

before:
![screenshot_2017-04-12_11-01-28](https://cloud.githubusercontent.com/assets/19060/24969861/78a9dbd0-1f6f-11e7-8263-8ab2708ca38c.png)
after:
![screenshot_2017-04-12_11-01-42](https://cloud.githubusercontent.com/assets/19060/24969867/7ae31a24-1f6f-11e7-84b5-7b2f6ceb514f.png)

**Comment by fniessen** [comment]
Dear @dakrone , would you wanna try setting `leuven-scale-outline-headlines` to `nil`?
