### ISSUE TITLE
I can not switch directly from leuven to leuven-dark

### ISSUE THREAD

**Issue by ReimuXMX** [fniessen/emacs-leuven-theme#47]
Your theme seems to write a lot of color configuration to custom-file .
So when I use `customize-theme` to switch to` leuven-dark`, the background color is still white ...

**Comment by ReimuXMX** [comment]
Sorry It's my bad. I should read the REAMDE

**Comment by hyiltiz** [comment]
Not sure where in README was it mentioned.
