### ISSUE TITLE
Dark theme improvement

### ISSUE THREAD

**Issue by seagle0128** [fniessen/emacs-leuven-theme#49]
I love leuven theme very much. It's great for org files especially. But the dark theme is not good as light theme. IMO It's too dark and not colorful.
Please improve and thanks in advance!

**Comment by ReimuXMX** [comment]
Although I am extremely disgusted with any "dark" theme, but I also feel that "dark" mode of leuven theme is too dark

**Comment by thblt** [comment]
leuven-dark is not more than a starting point: it was automagically generated by a script (`negate.py`, on the repo) which simply reversed luminance of each color of the original Leuven.  There's only so much this approach can do, and the dark theme currently would need some manual intervention.  I don't have time to do this myself, but it should be really easy to get something usable, by at least replacing `default`'s background color and fixing some contrast issues.  One may also want to look at constants in negate.py and test with other values.  I can help in understanding/improving the script, if needed :)

**Comment by svauban** [comment]
@ReimuXMX and @seagle0128 : if you feel like you can propose improvements, feel free!

**Comment by ReimuXMX** [comment]
I am happy to make a "PR", but I am a person with a color blindness and a very poor emacs-lisp level

So the colors I have chosen may be very weird ...


No matter what, I will try to improve.

**Comment by ReimuXMX** [comment]
@thblt 
About leuven-dark ...

I really think that the current script conversion is not good enough.

I suggest doing a separate package for leuven-dark, or make it like spacemacs-theme and color-theme-sanityinc-tomorrow.

At least allow users to simply convert "light" and "dark" through custom-theme. And can clean the point.
Now the leuven-theme is still some dirty - when I switch to other color themes, there are a lot of residual color settings.

**Comment by thblt** [comment]
@ReimuXMX 

> I really think that the current script conversion is not good enough.

I agree.  Again, it's a starting point.

> I suggest doing a separate package for leuven-dark

I maintain neither leuven nor leuven-dark,  I only drafted the dark version and contributed it here.  

> At least allow users to simply convert "light" and "dark" through custom-theme. And can clean the point.
Now the leuven-theme is still some dirty - when I switch to other color themes, there are a lot of residual color settings.

I don't understand the issue you have there.  Leuven-dark is completely independent from Leuven, but they share the very same code, modulo literal constants.  Residual settings usually come from themes not setting some faces, if that happen, you may want to use `disable-theme` to unset leuven[-dark]'s faces.

**Comment by ReimuXMX** [comment]
@thblt 

Oh, sorry, thank you for contributing leuven-dark, I am a bit rude.

I think you should talk to the original author of leuven about the conversion of `light` and` dark`.

On the third point ... I **DO NOT** refer to leuven-dark, but refer to the whole leuven theme.

Only leuven and monokai need to manually `disable-theme` in the theme I used.
For others, when I cancel the theme set, they seems that everything is good for me.

**Comment by thblt** [comment]
> I think you should talk to the original author of leuven about the conversion of light and dark.

I'm not sure I understand what more should be discussed :) If you want to see the original conversation, please see #32 and the linked issue.

> Only leuven and monokai need to manually disable-theme in the theme I used.

That's probably because they have a wider face coverage than most themes.    It may also be a bug, of course, but I doubt it.

**Comment by ReimuXMX** [comment]
Well, maybe I was not accurate enough ... because my English is very bad ... &
I am sorry for that.

> That's probably because they have a wider face coverage than most themes. It may also be a bug, of course, but I doubt it.

No ... I feel because their configuration is more conservative and narrow.

**Comment by thblt** [comment]
> I don't understand, sorry

**Comment by thblt** [comment]
> No ... I feel because their configuration is more conservative and narrow.

I don't understand, sorry.

**Comment by fniessen** [comment]
@thblt Thanks again for the starting point.

@ReimuXMX I don't have much time right now to try and debug problems. Though, if you can pinpoint things factually, I'd be ready to try and fix the problems.

I don't understand either what you mean by "configuration more conservative and narrow". If you can tell what should be done to revert that, please tell me.

Regarding a separate package, why not. A bit annoying, but not that much.

**Comment by fniessen** [comment]
Dear @seagle0128 , any chance you'd try to fix what you consider as not optimal?

**Comment by seagle0128** [comment]
Wow, I have a chance to try leuven-dark theme today. It looks much better. I am fine to close it. Thank you!

**Comment by fniessen** [comment]
OK - perfect!
