### ISSUE TITLE
No releases in MELPA-Stable

### ISSUE THREAD

**Issue by bzindovic** [fniessen/emacs-leuven-theme#50]
I have been using MELPA-Stable for some time but it seems to be missing Leuven-theme. Is it possible to add release tags and add your package to MELPA-Stable?

**Comment by fniessen** [comment]
(Late in the flow, but...) What should I do to make this happen? Just add a Git tag? Which one? Tried to find doc, but not yet found.
(I did well find this: #6656. Quid?)

**Comment by fniessen** [comment]
DONE.  Tagged as v1.1.0.

Thank you!

**Comment by bzindovic** [comment]
Thank you for providing the package to the community of MELPA-stable.

**Comment by fniessen** [comment]
@bzindovic You're welcome!
