### ISSUE TITLE
hidestars / org-indent-mode only hiding level 2 stars

### ISSUE THREAD

**Issue by cpbotha** [fniessen/emacs-leuven-theme#51]
With `#+STARTUP: hidestars`, orgmode hides the initial stars in headings. See the attached solarized-light theme rendering for an example of what this looks like. However, somehow this only works on level 2 headings for Leuven, with all deeper headings it does not manage to hide the leading starts.

``` org
#+STARTUP: hidestars

* level 1 heading

** level 2 heading

*** level 3

**** level 4

***** level 5
```

![image](https://user-images.githubusercontent.com/937871/33890727-bc74dc90-df5c-11e7-9b34-b67d7bdcad0d.png)

![image](https://user-images.githubusercontent.com/937871/33890742-c4c65bd0-df5c-11e7-91ce-b958dad11dae.png)

**Comment by fniessen** [comment]
![test-emacs-leuven](https://user-images.githubusercontent.com/1748469/34013595-62a74bea-e118-11e7-9257-512f1a95c890.png)

It works for me, without doing anything special.

Which version are you using?  The one built-in with Emacs, or the one from MELPA?  Try to look for the version number....

**Comment by cpbotha** [comment]
Thank you very much for getting back to me!

Seeing your example's background made me remember that I had edited my elpa-installed leuven-theme.el to have a slightly less bright background (the grey you can see in my example):

``` diff
@@ -148,7 +148,7 @@
   (custom-theme-set-faces
    'leuven
-   `(default ((,class (:foreground "#333333" :background "#FFFFFF"))))
+   `(default ((,class (:foreground "#333333" :background "#EFEFEF"))))
    `(bold ((,class (:weight bold :foreground "black"))))
    `(bold-italic ((,class (:weight bold :slant italic :foreground "black"))))
```

Most probably due to my limited understanding of emacs themes, this change somehow neutralised the org-hide setting / hiding mechanism.

You can close this issue. :) (If you have any tips why that single change breaks org-hide, I would be most grateful to hear them!)

**Comment by fniessen** [comment]
Dear @cpbotha , thanks for helping cleaning up… Much appreciated!
