### ISSUE TITLE
improve completion matching groups faces

### ISSUE THREAD

**Issue by stardiviner** [fniessen/emacs-leuven-theme#54]
As here a screenshot shows:

![image](https://user-images.githubusercontent.com/378699/37379329-0e852766-276e-11e8-8a1a-f35bbaa06ce2.png)

It looks not pretty, what do you think? Can you improve it?

**Comment by fniessen** [comment]
What command are you using?  Do you know which faces are in play?
You should find them with M-x list-display-faces. That'd help...

**Comment by stardiviner** [comment]
I'm using command `ivy-switch-buffer`. I did a search in leuven-theme, not found `ivy-` related faces. I found `helm-` faces are there. Will you add support for `ivy`?

**Comment by fniessen** [comment]
I don't use ivy myself. Can you try to make propositions?

**Comment by stardiviner** [comment]
I found ivy has many group conditions faces for matching. If only has two or three, I might suggest with a PR. I can't find a better color scheme for leuven-theme. So I just `set-face-attribute` on my init file personally. Sorry for distribution and thanks for your time.
