### ISSUE TITLE
Option to not supersize

### ISSUE THREAD

**Issue by muirdm** [fniessen/emacs-leuven-theme#55]
I love this theme, but I don't like the increased size in the `next-error` face since it pushes other text down momentarily as it highlights. Would it be possible to get an option to disable this, or alternatively a way to customize the theme where I can use the colors defined below`;; Leuven generic colors.` without needing to duplicate their definition in my customization?

**Comment by fniessen** [comment]
Dear @muirdm , set `leuven-scale-volatile-highlight` to `nil` to get your desired effect.
