### ISSUE TITLE
Highlight current line will cause some characters' bottom being invisible

### ISSUE THREAD

**Issue by RicardoMing** [fniessen/emacs-leuven-theme#60]
If I use the latest leuven theme, some characters' bottom will be invisable when I move to that line which contains such characters: (`g y q p`).
![mepla](https://user-images.githubusercontent.com/11895323/53927817-f0d78500-40c2-11e9-983f-43b1db542fe4.gif)
However, if I use the built-in leuven theme, there is no problem.
![buildin](https://user-images.githubusercontent.com/11895323/53927824-f59c3900-40c2-11e9-97fb-569950688ac6.gif)
I have test this with doom-emacs and vanilla Emacs, they all have this problem.

**Comment by fniessen** [comment]
Thanks for your clear example!  (You could have taken a more problematic one, with the underscore character…)

I know: it's because I've used underlining now (in a slightly darker yellow) for hl-line face.

I just removed that; it's true that it's less readable than before… Thx.
