### ISSUE TITLE
magit uses dark backgrounds for highlight lines

### ISSUE THREAD

**Issue by lvh** [fniessen/emacs-leuven-theme#61]
Hi! I'm not sure how to debug this but I figure a screenshot or two would speak a 1000 words.

![Screenshot from 2019-03-10 17-15-26](https://user-images.githubusercontent.com/97816/54092307-b555e880-4358-11e9-9326-e74be600359d.png)
![Screenshot from 2019-03-10 17-15-28](https://user-images.githubusercontent.com/97816/54092308-b555e880-4358-11e9-893d-85dea8d22921.png)

package-list-packages shows me as having:

```
  leuven-theme       20190308.1534 installed             Awesome Emacs color theme on white background
```

Other themes, like e.g. the spacemacs builtin themes, appear to theme this face to match the theme. I assumed leuven-theme would do as well because of the README, which mentions:

> “I love leuven for it’s magit faces. E.g. the different sections of the magit status screen stand out much better with leuven than with any other theme I’ve tried. It’s a good looking theme but what makes it stand out is the attention the author has put into all of the different faces you find everywhere.” 
> – UnwashedMeme

So presumably I'm not seeing the intended behavior :)

I hunted this down in magit and it appears it has a default for "light themes" and "dark themes" and somehow has decided that leuven is a dark theme?

**Comment by fniessen** [comment]
Dear @lvh , I'm not using magit -- I prefer the vc-dir interface which allows me to use the same key bindings.

If you do have a suggestion about what to change, let me know. I'll accept your PR.

**Comment by lvh** [comment]
Ugh, never mind: the issue was on my side. For some reason customize had value specifying all teams were dark, and just unsetting that fixed the issue. Sorry!

**Comment by fniessen** [comment]
Thanks for mentioning, and closing this!

**Comment by inducer** [comment]
FWIW, just had the same issue as @lvh, and, for me, the offending customize setting was
```
'(frame-background-mode (quote dark))
```
I figured I'd add that since it wasn't totally explicit in @lvh's comment. Otherwise, nothing to do here. Thanks for the theme!

**Comment by cpbotha** [comment]
Thanks for the tip @inducer !

According to the documentation, when `frame-background-mode` is set to `nil`, the default, Emacs will "examine the brightness for you". Does anyone have any ideas why this does not work for leuven, but it does work for other light themes?

**Comment by fniessen** [comment]
@inducer and @cpbotha, thanks for helping making this contribution still stand out!  And thanks for the nice comments - you know, after having copy/pasted some much code from all over the place, learning that way, it was my duty to share it with all of you.

As I said, I'm not using magit, though I know I could like it, but, having still SVN repos, I prefer one common way for accessing them all.

If you have suggestions for improvements, please send them…

(You may be interested having a look at some other projects of mine - namely git-leuven and shell-leuven - where I also share code for improving the experience in the shell, and with Git. As always, WIP, but a lot of good things is already in there.)
