### ISSUE TITLE
Create solarized leuven theme

### ISSUE THREAD

**Issue by codygman** [fniessen/emacs-leuven-theme#65]
Leuven is *very* complete, thank you for your great work!

It's not quite my visual taste though and I'd prefer to have the visual distinction leuven offers with more solarized style colors.

I guess I could just copy this repo and start changing colors to the solarized colors? I've never made an emacs theme and searching seems to point to that being the obvious and perhaps only solution here?

**Comment by fniessen** [comment]
Dear Cody,
 Thanks.   
You can do multiple things: fork this repo, and make your changes there, or copy the current repo and create a new one with another name, or make a pull request for introducing your flavor into my repo, with another name for the file...
  
Whichever...
  
For customizing the colors to your taste, that should be straightforward.   
  
Best regards.   
  
  

  
  
  
  
  
>
