### ISSUE TITLE
org src block background in emacs 27

### ISSUE THREAD

**Issue by merrickluo** [fniessen/emacs-leuven-theme#66]
pre emacs-27, org src block background covers the whole line, but now it seems only text has it.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/1495875/71649404-73fc5280-2d49-11ea-8241-15ec9f63d960.png">

**Comment by fniessen** [comment]
Dear @merrickluo, thanks for testing and mentioning this. However, this is not related to the Emacs theme, but to the way it's applied within Emacs.  So, the problem should be reported to the Emacs team, and maybe (?) also to the Org mode one (on the mailing list, for example).

Best regards!

**Comment by dakrone** [comment]
I believe this is a breaking change in Emacs 27 where faces now require `:extend t` to extend past the end of the line. Not necessarily a bug in Emacs.

**Comment by fniessen** [comment]
Dear @merrickluo , thanks for the context.

I've done what I think should be right. Feel free to test and to give me a feedback.

Best regards!

**Comment by merrickluo** [comment]
Thanks, @fniessen, and @dakrone, it's working perfectly now! closing issue.

**Comment by sangwon-hyun** [comment]
Hi! I'm wondering what happened to this fix (the current version -- either on github or on melpa version 1.1.2 -- doesn't have the :extend t anymore.)

My org mode blocks in emacs 27.1 still don't have the coloring extend beyond the line endings.

**Comment by fniessen** [comment]
Dear @sangwon-hyun ,

That property was finally removed completely from the theme in commit 

    afda2d8 Fabrice Niessen        2020-05-13 19:42 +0200 ∙ Apply last changes for integration into Emacs 27 

That was asked when pushing a new release of Leuven-theme in the Emacs trunk code - though I don't find the context for that request.

That's not fully clear to me ATM either, but I've seen that my theme does work correctly with org-plus-contrib. I guess you don't have that.
