### ISSUE TITLE
Can't use dark theme: Unknown theme 'leuven-dark'

### ISSUE THREAD

**Issue by riclage** [fniessen/emacs-leuven-theme#67]
I see the themes listed and can use the original leuven theme. However, when I try to install the `leuven-dark` theme, I get the message:

> Unknown theme 'leuve-dark'

This seems to be a similar issue as this user is facing: https://emacs.stackexchange.com/questions/52965/how-to-activate-leuven-dark-theme

The workaround proposed there also doesn't work for me.

**Comment by SNTag** [comment]
you should put here what you're doing to load the theme.  Also, is the error message actually stating 'leuve-dark'?

**Comment by riclage** [comment]
Thanks, I'm doing exactly what the answer I linked suggested:
```
  (load-theme 'leuven t)
```
Then load leuven-dark via
```
   M-x load-theme <RET> leuven-dark <RET>
```

> is the error message actually stating 'leuve-dark'?

yes.

**Comment by SNTag** [comment]
Finally got to a computer.  I don't use leuven-dark much, but I put together a hacky solution.

1.  Remove any previous Leuven installations.
2.  Download Leuven from Git as described in the ReadMe.
3.  From the downloaded leuven file, delete the file 'leuven-theme.el'  (note: you may want to run 'make-dark-theme.sh' first.  Not sure what the benefits are)
4.  In the file 'leuven-dark-theme.el', modify the line `(provide-theme 'leuven-dark)` to `(provide-theme 'leuven)`. The line is close to the very end of the file.
5.  Rename 'leuven-dark-theme.el' to 'levuen-theme.el'

It should now load as a dark theme.  There might be a better way, but the stack answer wasn't really working for me either.

**Comment by SNTag** [comment]
I think I've found a better way to enable leuven-dark.  I'll do some more tests later and pass my solution along to the authors once I'm certain it improves the theme.

**Comment by fniessen** [comment]
Dear @SNTag , if you wanna improve the README, you can send a Pull Request, and I'll gladly incorporate it!  Thanks...

**Comment by SNTag** [comment]
my suggested edits can be seen in pull request #68

**Comment by fniessen** [comment]
Merged. Thanks a lot!
