### ISSUE TITLE
Update package at Emacs

### ISSUE THREAD

**Issue by sergeyklay** [fniessen/emacs-leuven-theme#69]
Hello, 

First of all I'd like to say thank you for such great theme. The opinion that dark screen is helping to concentrate your eyes longer and helping your brain to keep more attention on the screen isn't worked for me. I do not need additional stimulants and I have a good concentration of attention. I prefer white themes because I have no reasons to use black ones and leuven is my choice for everyday usage. So thank you for such accurate theme.

I recently noticed that I lack functionality of `leuven-scale-outline-headlines` and  `leuven-scale-org-agenda-structure` which are part of latest versions presents on MELPA. The builtin version is a bit outdated and have no such functionality. 

So my question is could you please update builtin to Emacs leuven theme.

Thank you

**Comment by fniessen** [comment]
Dear @sergeyklay, thanks for the nice intro ;-)

You're right about the fact that Emacs builtin version is quite outdated. I can't commit anything myself, but I can well send a diff and try to get it updated.

On my TODO list.

Best regards,
Fabrice

**Comment by sergeyklay** [comment]
Ping. A friendly reminder for this :)

**Comment by b3n** [comment]
+1 I love this theme, and it would be amazing if it was updated before the release of Emacs 27.

**Comment by fniessen** [comment]
Dear all, I've just sent a patch file to the Emacs developers.

I dunno when it will be put in the core, but it's now on its way!

**Comment by fniessen** [comment]
bug#40759: Acknowledgement (26.3; Update Leuven-theme in Emacs dev trunk)

**Comment by sergeyklay** [comment]
Thank you!

**Comment by sergeyklay** [comment]
@fniessen We do need your attention here https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40759

**Comment by fniessen** [comment]
Dear @sergeyklay , I did send a patch 5 mins ago!  (Are you wanna tell something else?)

**Comment by sergeyklay** [comment]
@fniessen Nothing except thank you again!
