### ISSUE TITLE
Number of informational messages is hard to read

### ISSUE THREAD

**Issue by sergeyklay** [fniessen/emacs-leuven-theme#70]
Hello,

I propose to change color scheme a bit for the modeline. Presently the number of informational messages for a compilation mode is hard to read as the foreground color is close to the background color:

![image](https://user-images.githubusercontent.com/1256298/80256772-0f625c00-8688-11ea-83dc-c2d16b6be2b2.png)

I'd suggest to remove any colors at all here.

Thank you,
Serghei

**Comment by fniessen** [comment]
Fixed -- or intented to. Please check it out, and comment on it.
If you have a proposition, you also can submit it.

**Comment by sergeyklay** [comment]
Now it looks much better. Thank you for so quick fix!
