### ISSUE TITLE
magit mode background problem

### ISSUE THREAD

**Issue by ybgwon** [fniessen/emacs-leuven-theme#71]
I can't see charactor. Highlight line background is black in magit mode.  

![스크린샷 2020-05-05 15-29-35](https://user-images.githubusercontent.com/609090/81040002-60265000-8ee5-11ea-812b-1bddfe0a04ff.png)

Please fix this problem.
I love this theme.  Thank you.

**Comment by fniessen** [comment]
Hello. I don't use magit myself -- having to access SVN repos, I prefer vc-dir, which is universal for both SVN and Git (for me).
That said, please try to give me hints about what to change… Why is the highlight line black in magit?  Nobody reported that ATM. It's supposed to be a yellow background, why is it different in magit?  Do you have some face name I'd have to adapt. Please use `C-u C-x =` and check out for some useful names.

**Comment by ybgwon** [comment]
I tested other theme. zenburn, solarized ... But They are normal.
The following is result of 'C-u C-x =' 
https://gist.github.com/33a2306fd85c433e0f81f38d7eb39c98

I looked code similar your theme(modus).
https://gitlab.com/protesilaos/modus-themes
I think you need to add below code.
```
   `(magit-section-highlight ((,class (:background  "#F6FECD"))))
   `(lsp-ui-doc-background ((,class (:background "#F6FECD"))))
```
In lsp-mode you have problem.

**Comment by fniessen** [comment]
Thanks for coming with helpful data.
I've included those new faces into Leuven theme.
Pushed!
