### ISSUE TITLE
Markdown mode code formatting does not work

### ISSUE THREAD

**Issue by VJatla** [fniessen/emacs-leuven-theme#73]
![Screenshot from 2020-08-31 16-11-42](https://user-images.githubusercontent.com/57016272/91773892-dd688580-eba4-11ea-93c7-effd3bbc582b.png)

**Comment by SNTag** [comment]
Have you properly set up markdown-mode, or tried toggling markup? (its something like M-x markdown-toggle-markup)

look here for what i mean: 
https://emacs.stackexchange.com/questions/37858/how-do-i-hide-markup-in-markdown-mode-with-use-package

**Comment by fniessen** [comment]
@SNTag Thanks for helping!  (not related to Emacs Leuven Theme, btw...)

**Comment by VJatla** [comment]
I think the fonts and color used for code snippets was not easily
distinguishable from normal text.

Could you please explain how I can change the theme colors in markdown mode
?

Regards
Vj

**Comment by SNTag** [comment]
@VJatla
that is a more appropriate question for here.
options:
1. just edit the file 'leuven-theme.el'. you'r looking for 'markdown-inline-code-face'
2. I recommend using the function 'M-x describe-face' (see [here](https://www.emacswiki.org/emacs/Face) ). you can always look at this for other ways to modify faces: 
https://www.emacswiki.org/emacs/CustomizingFaces

@fniessen thanks!

**Comment by fniessen** [comment]
Dear @VJatla , can we close this?

**Comment by VJatla** [comment]
Yes, please close it.
