### ISSUE TITLE
leuven-dark parenthesis matching difficult to see

### ISSUE THREAD

**Issue by cddesja** [fniessen/emacs-leuven-theme#74]
It's extremely difficult to see the leuven-dark parenthesis matching. See the screenshot and compare with the leuven theme.

<img width="410" alt="Screen Shot 2020-09-19 at 10 08 23 AM" src="https://user-images.githubusercontent.com/1608939/93669173-1be4b800-fa60-11ea-96ae-d157279fcfd4.png">

<img width="418" alt="Screen Shot 2020-09-19 at 10 08 05 AM" src="https://user-images.githubusercontent.com/1608939/93669175-1e471200-fa60-11ea-9865-72ce880ba175.png">

Suggestions for how to improve this locally on my machine or updating it in the theme would be welcomed.

**Comment by fniessen** [comment]
Can you suggest a better RGB color code?
Then, I can add it to the theme.

**Comment by cddesja** [comment]
Thanks for the quick message back. Would RGB: 123, 75, 152 be better?  Maybe an intermediate purple? 

I don't think my original post was fair because I had my cursor in two different places. I changed this now. See below.

<img width="519" alt="Screen Shot 2020-09-19 at 10 34 57 AM" src="https://user-images.githubusercontent.com/1608939/93669690-dd50fc80-fa63-11ea-9d4e-0c511084fc0e.png">

**Comment by fniessen** [comment]
Check it out.  If needed, play with `paren-matched` value -- and come back here if you change it to a better value.
