### ISSUE TITLE
prompt color settings in shell-mode(comint-mode)

### ISSUE THREAD

**Issue by ouonline** [fniessen/emacs-leuven-theme#77]
Hi,

I customize PS1 in ~/.bashrc:

![modified](https://user-images.githubusercontent.com/856454/98499099-8b6a6d00-2283-11eb-90b1-f62649dcc5bc.png)

but leuven theme overrides my settings:

![orig](https://user-images.githubusercontent.com/856454/98498903-067f5380-2283-11eb-84cc-ce51e64ab983.png)

After removing the comint-mode settings I get what I want:

```diff
diff --git a/leuven-theme.el b/leuven-theme.el
index fd2298c..5ffcc22 100644
--- a/leuven-theme.el
+++ b/leuven-theme.el
@@ -402,9 +402,6 @@ more...")
    `(circe-originator-face ((,class (:foreground "blue"))))
    `(circe-prompt-face ((,class (:foreground "red"))))
    `(circe-server-face ((,class (:foreground "#99CAE5"))))
-   `(comint-highlight-input ((,class (:weight bold :foreground "#0000FF" :inherit nil))))
-   ;; `(comint-highlight-prompt ((,class (:weight bold :foreground "black" :background "gold"))))
-   `(comint-highlight-prompt ((,class (:weight bold :foreground "#0000FF" :inherit nil))))
 
    ;; `(ac-selection-face ((,class ,completion-selected-candidate)))
    `(ac-selection-face ((,class (:weight bold :foreground "white" :background "orange")))) ; TEMP For diff'ing AC from Comp.
```

I wonder if these settings can be removed to leave comint-mode prompt color unchanged.

**Comment by fniessen** [comment]
It's nice to have the prompt highlighted correctly and consequently between different environments (R, emacs-lisp subsystem maybe... and the Shell). But I understand your problem and do not see other solution than to remove these settings from my theme.

Thanks for using it!

**Comment by ouonline** [comment]
> It's nice to have the prompt highlighted correctly and consequently between different environments (R, emacs-lisp subsystem maybe... and the Shell). But I understand your problem and do not see other solution than to remove these settings from my theme.
> 
> Thanks for using it!

I have been using Leuven(the version released with Emacs, though a little old) as my default theme for several years. It is an amazing theme for me. Thanks for sharing :)
