### ISSUE TITLE
melpa build broken

### ISSUE THREAD

**Issue by egh** [fniessen/emacs-leuven-theme#80]
The MELPA build is broken because the `.el` files moved into `lisp/`. Here is a fix for MELPA:

```patch
diff --git a/recipes/leuven-theme b/recipes/leuven-theme
index 573b6b3f..586e759a 100644
--- a/recipes/leuven-theme
+++ b/recipes/leuven-theme
@@ -1,3 +1,4 @@
 (leuven-theme
  :fetcher github
- :repo "fniessen/emacs-leuven-theme")
+ :repo "fniessen/emacs-leuven-theme"
+ :files ("lisp/*.el"))
```

I am happy to file a PR at MELPA if you like.

**Comment by fniessen** [comment]
Der @egh , Thanks a lot for the fix - and, yes, I'd love it if you could file a PR at MELPA.
Pretty in overdrive ATM!
Thanks in advance...
