### ISSUE TITLE
misalignment in org column mode

### ISSUE THREAD

**Issue by westofer** [fniessen/emacs-leuven-theme#82]
expected:
![image](https://user-images.githubusercontent.com/50760091/108190256-c1d94300-7122-11eb-9c5c-9352464315f0.png)
actual:
![image](https://user-images.githubusercontent.com/50760091/108190509-14b2fa80-7123-11eb-93a6-dd988bc2fd9a.png)

**Comment by westofer** [comment]
solved by #43
sorry

**Comment by fniessen** [comment]
Thanks for confirming!
