### ISSUE TITLE
Agenda font-color of "WAIT" is dark black

### ISSUE THREAD

**Issue by herop** [fniessen/emacs-leuven-theme#83]
I just recently came to enjoy your theme veeery much I must admit.
Contrary to your screenshot, my agenda `WAIT` looks very different.
Please help me out here?

Thank you in advance and kudos for your wonderful theme that is about to become my standard!

![Screenshot from 2021-03-18 19-40-38](https://user-images.githubusercontent.com/658323/111680718-ca589280-8822-11eb-83e3-76fd3c133056.png)

**Comment by fniessen** [comment]
Dear @herop , WAIT is not an official Org keyword. I've done it mine, in my Org config.
See https://github.com/fniessen/emacs-leuven/blob/e89e409fd1598688fe3a233d06fc627aca15f436/emacs-leuven-org.el#L462 and following lines...
PS - I'd advice you to keep all your keywords 4-char long, to get a perfectly aligned screen!

**Comment by herop** [comment]
Can't thank you enough for your immediate and - as expected - perfectly working advice!
One more thing:
![Screenshot from 2021-03-19 12-02-35](https://user-images.githubusercontent.com/658323/111770796-26ff9000-88ab-11eb-8bb1-c68fcb2f99c6.png)
Since this is barely recognizable as a green badge with a `t` in it, I did some digging and found, that moving the mouse over it would make it appear.
Any idea why this might happen?
Thank in advance for your replay and have a wonderful day,
Jochen

**Comment by herop** [comment]
Arghh, I lied:
Your using the `org-todo-keyword-faces` doesn't do the trick for me.
Would you think it's my config?
![Screenshot from 2021-03-19 12-29-12](https://user-images.githubusercontent.com/658323/111774025-2ec13380-88af-11eb-89fd-cb272c328e2a.png)
Because I receive the following error with the setting active:
![Screenshot from 2021-03-19 12-33-36](https://user-images.githubusercontent.com/658323/111774178-692ad080-88af-11eb-9194-68ed77b25491.png)
![Screenshot from 2021-03-19 12-33-57](https://user-images.githubusercontent.com/658323/111774191-6cbe5780-88af-11eb-89f9-a7aafa97357f.png)

**Comment by herop** [comment]
I'm near certain you don't want to hear ever of me again. :-)

But this time I have good news: This might be true after all. I fixed my `WAIT` color issues with this minimal snipped from your config:
![Screenshot from 2021-03-19 20-17-32](https://user-images.githubusercontent.com/658323/111832203-c5faab00-88f0-11eb-93f1-39f87aef45a5.png)
Punched in a (after! org ... ) and - boom, it works.
Thank you again for your truly outstanding theme - the only true winner of light themes!
Kind regards,
Jochen

**Comment by fniessen** [comment]
Cool you got it!

PS - Not sure to understand your post with the green badge.  Make a new issue, if there really is an issue.

PPS - I'm using powerline-leuven-theme.

PPPS - I'm planning to build a course on tips and tricks to boost your Emacs productivity. Would that interest you?

**Comment by herop** [comment]
1) Not enough to bother you ☺️
2) Your comment on the powerline theme I didn't get
3) Absolutely

**Comment by herop** [comment]
Got it reg. Powerline theme ☺️
Just failed to implement it. 😳
You see an easy way to help me out here?
Your config is very nice and quite extensive, but I couldn't figure it on myself. 
Maybe I don't need it? Or would you see big benefits?

**Comment by fniessen** [comment]
@herop See https://github.com/fniessen/emacs-leuven/blob/e89e409fd1598688fe3a233d06fc627aca15f436/emacs-leuven.el#L1506 and following lines...

**Comment by herop** [comment]
I know, I know...
Status:
- I activated the Package "powerline" in Doom
- I read your config thoroughly and put the lines you referred to in my config 1506 to 1615
- Then tested (no errors), synced started aaaand...
- No change in the Powerline / Modline / Icons
- If you look at my screenshot from above closely, you will see the green parts are not recognizable 
- Likewise, If I activate doom-modeline-icon they will show up in the same green - and are nearly invisible

What you say?
- Is this green not intended 
- Are the modeline icons not supported
- Do I need to activate the powerline with something like setq?

Thank you so much for all your work and support. 
I just won't use another theme 'cause I'm such a fan!

Kind regards,
Jochen

**Comment by fniessen** [comment]
Dear @herop, I don't know Doom.
I'd say: try with my emacs-leuven config, to see what you're getting.
And, depending on the output, you could have hints on where/how to debug your problem.

Best regards!

**Comment by herop** [comment]
Thank you - again for your immediate help!
I do not have a problem, it's just - cosmetics.

You mean the complete config?

I already use the mentioned part.
Well, if you could tell me how to change the dark blue (refer to the screenshot above) value in something like light orange, I would just as happy.
(Digging and digging, I couldn't find the matching color-code in the source.)

What u say? 
Best regards,
Jochen

**Comment by fniessen** [comment]
Yes, I meant the whole config.

But, for your question, see face "mode-line" in the theme.

**Comment by herop** [comment]
Knew it, you would deliver. Thank you so much!!
Found the mode-line and punched in an extremely aggressive orange.
Now, you made me - again - an incredibly happy Emacs-User (and leuven fan).

Tried to find any theme, but none is even close.

Allow me to sponsor your amazing work with a small sum. (On it)

One more thing: using your config won't work with me I think, since I'm a DOOM user with evil-mode.
But will definitely steal some more of your great ideas...

**Comment by herop** [comment]
defface is a wonderful tool but won't work for me.
Can you pls. provide more details? Changing *.el isn't the best idea, right:

`(defface mode-line
  '((t (:box (:line-width 1 :color "#1A2F54") :foreground "green" :background "DarkOrange")))
  "Orange and green colors in mode-line.")`
Can you please tell me, why this is not working even though this does:
`(setq org-todo-keyword-faces
      '(("WAIT" . leuven-org-waiting-for-kwd)))
;; Mode-line colors
;; Org non-standard faces.
(defface leuven-org-waiting-for-kwd
  '((t :weight bold :box "#89C58F"
       :foreground "#89C58F" :background "#E2FEDE"))
  "Face used to display state WAIT.")`

**Comment by fniessen** [comment]
Dunno if that could be the explanation, but don't expect to change a defface definition, and see the change immediately, even after C-x C-e (after the last parenthesis).

You need to restart Emacs (or, better, launch another instance) to see the results...

**Comment by herop** [comment]
I did of course. Syncing, restarting ...
It doesn't apply at all.
Esp. since updates reset any change I make to the original file, I try to find a solution for this.
Any further advice?

**Comment by fniessen** [comment]
Re-reading this whole thread (which deviates a lot from the original subject), I see that:
- you're able to define new faces, the way I did for the WAIT keyword
- you're not able to redefine mode-line.
right?

I guess it's normal: mode-line is defined by standard in Emacs.  Though it's not clear from the doc of defface, I guess you can't redefine a face that already exists - that would make sense.

So, if you want to customize it, this must be done via a theme, like mine, or via a customize-face command call, OK?

**Comment by fniessen** [comment]
Feel free to leave a tip if you enjoy this theme!

(If you have another issue, unrelated to the original one here, please submit a new one.)

**Comment by herop** [comment]
Just a final note:
I did leave a tip of EUR30 on the 19th of April. Hope you received it?
Thanks again for your wonderful work and have a great day

**Comment by fniessen** [comment]
Dear Jochen, yes I did get it. Highly appreciated!
