### ISSUE TITLE
Move files to "lisp/" directory breaks custom-theme-load-path

### ISSUE THREAD

**Issue by JiaHong-Lee** [fniessen/emacs-leuven-theme#84]
Hi, I am using the Git version of this beautiful theme. The way I use it is as suggested in README:
```emacs-lisp
(add-to-list 'custom-theme-load-path "/path/to/emacs-leuven-theme")
(load-theme 'leuven t)                  ; For Emacs 24+.
```
Today, after pulling, I couldn't load 'leuven-dark theme. After a little bit of tinkering, I find out it's caused by https://github.com/fniessen/emacs-leuven-theme/commit/4820d461fae105c0f192bd0194bb7022eb527f33. I can make it works again either by
1. Using `(add-to-list 'custom-theme-load-path "/path/to/emacs-leuven-theme/lisp")`.
2. Move the leuven-theme files to `/path/to/emacs-leuven-theme`.

Personally, I'll suggest the second  solution since it works well with other themes such that I can simply load all the themes in this way:
```emacs-lisp
(setq custom-theme-directory (concat user-emacs-directory "themes/"))
(dolist (subdir (directory-files custom-theme-directory t ".*-theme"))
  (add-to-list 'custom-theme-load-path subdir))
```

--- Cheers, happy hacking.

**Comment by fniessen** [comment]
Dear @JiaHong-Lee, thanks a lot for the report, and suggestions.

I understand your preference, though I've chosen the first one, for one reason: I'm using now Dotfiler (see https://github.com/svetlyak40wt/dotfiler) to "stow" files from repos under a single place in my HOME directory, and I'd like all my Lisp files to land into my ~/lisp directory.
