### ISSUE TITLE
Shipping leuven-dark-theme.el with Emacs?

### ISSUE THREAD

**Issue by skangas** [fniessen/emacs-leuven-theme#92]
Hi Fabrice,

I have opened a [bug report against GNU Emacs](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53032) about shipping leuven-dark-theme.el with Emacs:

```
Severity: wishlist

leuven-theme.el is shipped with Emacs, but its sibling theme
leuven-dark-theme.el is not.

Is there any reason not to add leuven-dark-theme.el to Emacs?
```

It unfortunately seems like your email adress bounced, so I'm opening this issue as well.

**Comment by fniessen** [comment]
Dear @skangas,

Indeed, that email address does not work anymore - too much spam received on it.

For the point at hand, yes, I fully am OK for including the dark theme within Emacs as well.

Do I have to do anything?  Or will you report this statement to the bug tracker, and that will be sufficient?

Best regards!

**Comment by skangas** [comment]
Thanks! I will forward this information to the bug tracker. There should be nothing else to do but just copying the file, right? All the copyrights are in order with proper assignments as needed, and so on?

**Comment by fniessen** [comment]
Dear @skangas,

Yes, everyting's OK -- the file is a copy of the light version, except for the colors, of course! ;-)

**Comment by skangas** [comment]
Excellent!

**Comment by skangas** [comment]
Hmm, so I tried adding it to Emacs as a new file `etc/themes/leuven-dark-theme.el` but it ended up that when I do `M-x load-theme RET leuven-dark RET`, I get:

```
append: Symbol’s function definition is void: leuven-scale-font
```

**Comment by fniessen** [comment]
@skangas , should be fixed... Typo on my side...

**Comment by skangas** [comment]
Now added!
https://git.savannah.gnu.org/gitweb/?p=emacs.git;a=commit;h=7728f493cd1416bac45be4b4495c989e12caf3ac

**Comment by fniessen** [comment]
@skangas Thanks a lot!
