### ISSUE TITLE
Wrong URL in leuven-dark-theme.el

### ISSUE THREAD

**Issue by dr-scsi** [fniessen/emacs-leuven-theme#93]
The URL in `leuven-dark-theme.el` goes 404.  It currently says:

https://github.com/fniessen/emacs-leuven-theme/blob/10be661cbf149ec173dfc6371702fb394143ae1c/lisp/leuven-dark-theme.el#L7

where `leuven-theme.el` says:

https://github.com/fniessen/emacs-leuven-theme/blob/10be661cbf149ec173dfc6371702fb394143ae1c/lisp/leuven-theme.el#L6

which works.

**Comment by fniessen** [comment]
Dear @dr-scsi , should be fixed. Thanks for reporting!

**Comment by dr-scsi** [comment]
Thanks for the quick fix 👍
