### ISSUE TITLE
Customization doesn't work with dark theme

### ISSUE THREAD

**Issue by mrcnski** [fniessen/emacs-leuven-theme#99]
Hello, it seems the [customization options](https://github.com/fniessen/emacs-leuven-theme#customize-it) don't work with the dark theme. (I prefer the unscaled headings... :P) 

Thanks for the theme!

**Comment by fniessen** [comment]
That's possible -- as I'm not using it.

Would you mind porting the couple of lines to it, and sending a PR?

**Comment by mrcnski** [comment]
Hi Fabrice, I wouldn't mind at all. Cheers!Sent from my iPhoneOn 12 Jun 2023, at 11:04, Fabrice Niessen ***@***.***> wrote:﻿
That's possible -- as I'm not using it.
Would you mind porting the couple of lines to it, and sending a PR?
